
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZERveXo0UnMxbE13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNU1EWXlNRFU0TURGYUZ3MHpOREE1TURReU1UQXpNREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUREUW9rR1pQeEEvaGpXU3ozd2l6Q2Q0SEd6MWFjQnRSaEtybXlNWnhiaEZiNVRhRDN1cVFCL21rMTAKOXVjclVXdDRZT0hOeWMxTXhjWlh6dSswSVdiaUJ4M2FFVnhNOEQ3ME4xSy9maUhGNWk5WlIraVR2ZzFIamxXMwpwTDd4TnhYNjVCS2Y0V0VyL0VoQkFLanUxN0JLZFU2RHlBem9KMmN0c1lOOFA5enlyY21vZ0l0b3AxZ0NwbFRhCmlXOTkzYXZuSjZmR3JIRm9mTFEwM3VBek5YbkpDQzA3alNCYUtLSVdMT01ucmJ4WlJNdW0zZ2lYWjB2T2s4ZnUKa3B3cUIwc2VmTnVoUXNleFBiUlJERXd6OFVXQnNMVFBRNDhTTEZKeVZXV0RoeDY1czhaZGwzelZ1cEZRMFA1cwoyK1J1K0lkZ0l6VGs0aE41byswd0pnajZucHczQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRNW1kamhSQ3hDZE5WS0lIQUZFQlZXK2JKUk5UQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmIvVzJ3bjRqYQowa3YrSVRocHhBMkc5bTRJZVlLVVBkOUxrMzJ3ZVRHU3piMWpZek5jUUNVRDFRV1dwbFFQdCs1ZzFEUkFxVzRtCjRiQWxWcGliVjdla1dmditpOENTQ1NpbENMMHV0NkR1THQxMm1RcXhXNnVzWmNNcys4NlRta3gzVmZGbmw3ZHkKWG5xaFdaVHZSZTFXRXh2dDdraTlkV1lKSng5YTYwNnpFRGRTUHh2c214Z0RHMHdoMXVmamswZ0gyUTd2dkpQUwozc3VwaHpJQVFsMU5uSnZRaUlOME0wK2ZyMkFtK3hGVHZSZ3BjKzQ5eFBKWXRXSDN3YXVuUTd4K1RSNHBETnBLCldvZ2JOQjkzWktLWjFlTU05YldYTGd1MWsvQmVxTTk1S1YxM1p0WFZVcVNGa0hqTHByMFgzZWFJdlljRS9lYVIKVURnbEFlRll2UGwvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://747aca13-eba3-418b-a3a1-f3990180c9fa.ca-central-1.linodelke.net:443
  name: lke225222

users:
- name: lke225222-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IklQNjdMYy1ZNnhhRWwyeE9VdEl2LXRVNk9ocWFfS2Z2MW1iaEQ4RElqQncifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tczJsa3EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZTc2OTA5NGItNGRlOC00ZTk3LWE3MDEtM2NhNDE4YzMzODM1Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.X994lQkRfgOQncEczqwMxeqOv-IEpo1znBS2MDRXBiwt96zKpi-2yx4UwXJHMcXMExCPxqmvjAFeEbvXpA9fxeN1EeCLQoNCgezKnwvY6L2Yfx0Ad96XVwuuPuMOJ2YGZwSUp5hV8hboBV8r13xmDDEFEgx05vYNkbI1JNzDdQkyvkJ3Kxay0QS2t5idp9CrclVtY4iJl47img_U2nMyMCPXFcXI4FdRRhRLWkgu1Wy-t5gAz7_pYao2qk_DYsUqIn4YAK-NzWzZfIX9Fa2fGb-hOJGKeKUHA2lQ25phY2x-EsFny9abQI8WNgnCaTDJE7t_okT_m5sJetafGoPkVw

contexts:
- context:
    cluster: lke225222
    namespace: default
    user: lke225222-admin
  name: lke225222-ctx

current-context: lke225222-ctx
